graphhopper:
  datareader.file: india-rail.osm.pbf
  graph.location: ./graph-cache
  custom_models.directory: ./custom_models

  graph.encoded_values: >-
    gauge,voltage,electrified,frequency,road_environment,
    max_speed,rail_access,rail_average_speed,
    railway_class,railway_service,preferred_direction

  profiles:
    - name: rail
      custom_model_files: [alltracks.json]
      turn_costs:
        vehicle_types: [train]
        u_turn_costs: 60

  profiles_ch:
    - profile: rail

  server:
    application_connectors:
      - type: http
        port: 8989
    admin_connectors:
      - type: http
        port: 8990
